### ISSUE TITLE
NotImplementedError when running any dbt command after dbt-mysql installation

### ISSUE THREAD

**Issue by the-timoye** [dbeatty10/dbt-mysql#115]
I use python version 3.10.7 & pip version 22.2.2

I get a NotImplementedError whenever I try to run any dbt command after installing dbt-mysql with the `python -m pip install dbt-mysql` commannd. I can't even run the `dbt init` command successfully

### Steps To Reproduce
- python -m venv venv          # create a virtual environment
- python -m pip install dbt-mysql         # install dbt-mysql
- dbt init

### Expected behavior
I should be able to initialize dbt

### log output
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\<username>\Documents\dummy_db_docs\venv\Scripts\dbt.exe\__main__.py", line 4, in <module>
  File "C:\Users\<username>\Documents\dummy_db_docs\venv\lib\site-packages\dbt\main.py", line 2, in <module>
    from dbt.logger import GLOBAL_LOGGER as logger, log_cache_events, log_manager
  File "C:\Users\<username>\Documents\dummy_db_docs\venv\lib\site-packages\dbt\logger.py", line 16, in <module>
    from dbt.dataclass_schema import dbtClassMixin
  File "C:\Users\<username>\Documents\dummy_db_docs\venv\lib\site-packages\dbt\dataclass_schema.py", line 13, in <module>
    from mashumaro import DataClassDictMixin
  File "C:\Users\<username>\Documents\dummy_db_docs\venv\lib\site-packages\mashumaro\__init__.py", line 4, in <module>
    from mashumaro.serializer.json import DataClassJSONMixin
  File "C:\Users\<username>\Documents\dummy_db_docs\venv\lib\site-packages\mashumaro\serializer\json.py", line 28, in <module>
    class DataClassJSONMixin(DataClassDictMixin):
  File "C:\Users\<username>\Documents\dummy_db_docs\venv\lib\site-packages\mashumaro\serializer\base\dict.py", line 21, in __init_subclass__
    raise exc
  File "C:\Users\<username>\Documents\dummy_db_docs\venv\lib\site-packages\mashumaro\serializer\base\dict.py", line 17, in __init_subclass__
    builder.add_to_dict()
  File "C:\Users\<username>\Documents\dummy_db_docs\venv\lib\site-packages\mashumaro\serializer\base\metaprogramming.py", line 365, in add_to_dict    
    pre_serialize = self.get_declared_hook(__PRE_SERIALIZE__)
  File "C:\Users\<username>\Documents\dummy_db_docs\venv\lib\site-packages\mashumaro\serializer\base\metaprogramming.py", line 203, in get_declared_hook
    if type_name(cls) != DataClassDictMixinPath:
  File "C:\Users\<username>\Documents\dummy_db_docs\venv\lib\site-packages\mashumaro\meta\helpers.py", line 28, in type_name
    if is_generic(t):
  File "C:\Users\<username>\Documents\dummy_db_docs\venv\lib\site-packages\mashumaro\meta\helpers.py", line 54, in is_generic
    raise NotImplementedError
NotImplementedError

**OS: Windows 10**
**Python Version: 3.10.7**
**Pip Version:22.2.2**

**Comment by the-timoye** [comment]
Found a solution. 

dbt-mysql works only with PY3.6 - PY3.9.
