### ISSUE TITLE
Issue with dbt-mysql installation

### ISSUE THREAD

**Issue by arielcesante** [dbeatty10/dbt-mysql#98]
Hi,

Anyone encountered this issue when trying to install dbt-mysql via pip?

Collecting dbt-mysql
  Using cached dbt_mysql-0.19.2-py3-none-any.whl (53 kB)
Collecting dbt-core==0.19.2
  Using cached dbt_core-0.19.2-py3-none-any.whl (792 kB)
Collecting mysql-connector-python<8.1,>=8.0.0
  Using cached mysql_connector_python-8.0.30-cp310-cp310-win_amd64.whl (7.9 MB)
Collecting Jinja2==2.11.2
  Using cached Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
Requirement already satisfied: isodate<0.7,>=0.6 in c:\users\d1338529\appdata\local\programs\python\python310\lib\site-packages (from dbt-core==0.19.2->dbt-mysql) (0.6.1)
Requirement already satisfied: minimal-snowplow-tracker==0.0.2 in c:\users\d1338529\appdata\local\programs\python\python310\lib\site-packages (from dbt-core==0.19.2->dbt-mysql) (0.0.2)
Collecting mashumaro==2.0
  Using cached mashumaro-2.0.tar.gz (25 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting cffi<1.15,>=1.9
  Using cached cffi-1.14.6.tar.gz (475 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\d1338529\AppData\Local\Temp\pip-install-5gpn7iqn\cffi_6fac88013d854393b3527a6fa084239f\setup.py", line 127, in <module>
          if sys.platform == 'win32' and uses_msvc():
        File "C:\Users\d1338529\AppData\Local\Temp\pip-install-5gpn7iqn\cffi_6fac88013d854393b3527a6fa084239f\setup.py", line 105, in uses_msvc
          return config.try_compile('#ifndef _MSC_VER\n#error "not MSVC"\n#endif')
        File "C:\Users\d1338529\AppData\Local\Programs\Python\Python310\lib\distutils\command\config.py", line 225, in try_compile
          self._compile(body, headers, include_dirs, lang)
        File "C:\Users\d1338529\AppData\Local\Programs\Python\Python310\lib\distutils\command\config.py", line 132, in _compile
          self.compiler.compile([src], include_dirs=include_dirs)
        File "C:\Users\d1338529\AppData\Local\Programs\Python\Python310\lib\distutils\_msvccompiler.py", line 323, in compile
          self.initialize()
        File "C:\Users\d1338529\AppData\Local\Programs\Python\Python310\lib\distutils\_msvccompiler.py", line 220, in initialize
          vc_env = _get_vc_env(plat_spec)
        File "C:\Users\d1338529\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\msvc.py", line 316, in msvc14_get_vc_env
          return _msvc14_get_vc_env(plat_spec)
        File "C:\Users\d1338529\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\msvc.py", line 270, in _msvc14_get_vc_env
          raise distutils.errors.DistutilsPlatformError(
      distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by dbeatty10** [comment]
Hi @arielcesante 👋 

I suspect the key part of the error message is this:

> Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

Could you try clicking that link and installing the Microsoft C++ Build Tools to see if that helps with your install?

**Comment by arielcesante** [comment]
Hi Dougg,

Thanks for the reply! Yes I have resolved the issue soon after I installed that Microsoft Visual C++ 14.0

Regards!
Ariel

**Comment by dbeatty10** [comment]
Awesome, Ariel -- glad to hear that!
